//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionPuntoDeVenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvInventario
    {
        public int IdInventario { get; set; }
        public int IdProducto { get; set; }
        public decimal Cantidad { get; set; }
        public int IdUnidad { get; set; }
        public decimal Precio { get; set; }
        public int IdCantTaco { get; set; }
    
        public virtual InvCantidadPorTaco InvCantidadPorTaco { get; set; }
        public virtual InvProducto InvProducto { get; set; }
        public virtual InvUnidadMed InvUnidadMed { get; set; }
    }
}
