//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionPuntoDeVenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public int IdUser { get; set; }
        public Nullable<int> IdPromo { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> Qty { get; set; }
        public decimal FinalAmount { get; set; }
        public System.DateTime dDateTime { get; set; }
        public Nullable<bool> bActive { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> IdParent { get; set; }
    }
}
